### Users
GET http://localhost:1234/users

### Users by Id
GET http://localhost:1234/users/user-1

### Users by genre
GET http://localhost:1234/users?lastname=Gómez

### POST
POST http://localhost:1234/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXItMiIsImVtYWlsIjoibWFydGluLnJvZHJpZ3VlekBleGFtcGxlLm5ldCIsImlhdCI6MTc0NzE1MTEzNCwiZXhwIjoxNzQ3MTU0NzM0fQ.qX9ybpkvC4El_c0jdVEum9FEuu0tHY5x_dagjWsVluc

Content-Type: application/json

{
      "name": "Luciano",
      "lastname": "Gomez",
      "birthday_year": 2001,
      "address": "Entre Rios 1234",
      "email": "LucianoGomez@gmail.com",
      "password": "LucianoGomez123!"
    }

### PATCH
PATCH http://localhost:1234/users/4b980335-1fed-433b-a79e-accfc31557e0
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InVzZXItMiIsImVtYWlsIjoibWFydGluLnJvZHJpZ3VlekBleGFtcGxlLm5ldCIsImlhdCI6MTc0NzE1MTEzNCwiZXhwIjoxNzQ3MTU0NzM0fQ.qX9ybpkvC4El_c0jdVEum9FEuu0tHY5x_dagjWsVluc

Content-Type: application/json

{
    "birthday_year": 2000,
    "address": "El cabure 10"
}